forms with validation and errors
Skobraf/re-former pull request #1
Opened 2018-06-26 16:04 UTC by Skobraf

2018-06-27 13:22 UTC, jklemon17 requested changes
Good work overall, just a few changes need to clean things up. Then we'll look at testing :smile: . Oh, and please update the README file to describe the project (even though it is a simple one). Getting into the habit of writing good READMEs is important.

2018-06-27 13:22 UTC, jklemon17 commented on app/controllers/users_controller.rb
> +      redirect_to user_path
This should be `redirect_to @user`, like you have in the update action below. Right now, I get an error when I create a new user. (When using `user_path`, you must pass it the id of the user. In practice, it's usually easier to just pass the user object instead of using user_path.)

2018-06-27 13:22 UTC, jklemon17 commented on app/helpers/users_helper.rb
> +module UsersHelper
Please delete auto-generated files if they are not being used (not a big deal on a small project like this, but imagine when you're working on something big and have dozens of empty files...)

2018-06-27 13:22 UTC, jklemon17 commented on app/controllers/users_controller.rb
> +      render :new
If the update fails, it should `render :edit`, not :new. If I try to update with invalid data, it takes me to the 'new' form, and I get an error when I then submit valid data.

2018-06-27 13:22 UTC, jklemon17 commented on app/views/users/new.html.erb
> +<%= form_for @user, url: {action: 'create'} do |f|%>
You don't need the `url: {action: 'create'}` statement here. In fact, to re-use the form on both the 'new' and 'edit' pages, you need to remove it.

2018-06-27 13:22 UTC, jklemon17 commented on app/views/users/edit.html.erb
> +<%= form_for @user do |f|%>
After fixing the redirect in the 'update' action, your edit page no longer displays error messages (actually, it never did - the new page was being rendered and showing them). To solve this and take advantage of a great Rails feature, extract your form into a partial. You can then just render the partial on each of the views, and Rails intelligently knows whether it should perform a create or update (based on whether the user object is in the database). Let me know if you need any help with this.

2018-06-27 13:22 UTC, jklemon17 commented on app/views/users/show.html.erb
> +<h1><%=@user.password%></h1>
It would be a good idea to put a link to the edit page here, since currently the only way to get to it is to type it directly into the nav bar.

2018-06-27 13:22 UTC, jklemon17 commented on app/views/users/update.html.erb
> +<h1><%=@user.username%></h1>
This view is unused and not needed.

2018-06-27 13:22 UTC, jklemon17 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
You should set a root route, so users are not taken to the default Rails landing page. `users/new` would be a good root for this project.

2018-06-27 13:22 UTC, jklemon17 commented on test/controllers/users_controller_test.rb
> +require 'test_helper'
I'll comment on testing after the other changes have been made. I think it would be good to merge the app files into the master after the changes are made, then create a new branch and pull request for testing.

2018-06-28 15:47 UTC, jsgilberto commented on test/controllers/users_controller_test.rb
> +require 'test_helper'
Thanks for your feedback! we are going to fix it asap!

2018-06-28 16:22 UTC, jsgilberto commented on test/controllers/users_controller_test.rb
> +require 'test_helper'
The issues you mentioned before are fixed (I think so), we only need to change the readme file!

2018-06-28 16:54 UTC, jsgilberto commented
Is it better practice to use 'flash' to display messages instead of what we did here?

```+<% if @user.errors.full_messages %>
+  <ul>
+  <%@user.errors.full_messages.each do |error| %>
+    <li><%= error %></li>
+  <%end%>
+  </ul>
+<%end%>```

2018-06-28 17:08 UTC, jklemon17 commented
Actually, something like you did is the recommended approach. That way you can position it in the appropriate place on the page (since the flash typically renders just at the top, or some fixed place in the layout file). The errors piece can actually be pulled out into a partial so that it can be used by other models as well. You don't need to do that here, but may want to keep it in mind for upcoming projects.

2018-07-03 19:21 UTC, jklemon17 commented
Go ahead and merge this PR, then create a new branch for testing. You'll want to test with RSpec, not the default with Rails test folder. Test the **model** and the **controller**. I wouldn't worry about the views or feature testing at this point.

2018-07-07 22:24 UTC, merged